### ISSUE TITLE
Improve french support

### ISSUE THREAD

**Issue by Brndan** [reutenauer/polyglossia#12]
The french support in polyglossia is quite limited.

I suggest to add some commands which will help to get back some of the functionnality one could find using the `babel` package:

> \def\ier{\textsuperscript{er}}
> \def\iers{\textsuperscript{ers}}
> \def\iere{\textsuperscript{ère}}
> \def\ieres{\textsuperscript{ères}}
> \def\ieme{\textsuperscript{e}}
> \def\iemes{\textsuperscript{es}}
> \def\nd{\textsuperscript{nd}}
> \def\nds{\textsuperscript{nds}}
> \def\nde{\textsuperscript{nde}}
> \def\ndes{\textsuperscript{ndes}}
> \def\no{\textsuperscript{o}}
> \def\nos{\textsuperscript{os}}
> 
> \def\mme{M\textsuperscript{me}\space}
> \def\mmes{M\textsuperscript{mes}\space}
> \def\mr{M.\space}
> \def\mrs{MM.\space}

I also add the following suggestion in order to produce  produce footnotes “à la française” (often mandatory for humanities):

> \renewcommand\@makefntext[1]{%
>  \noindent\makebox[1em][r]{\@thefnmark.\space}#1}

This code must be added to the file `gloss-french.ldf`.

**Comment by hugoroy** [comment]
This is fixed. cc @reutenauer

**Comment by maieul** [comment]
please, make this optional. Many time time people could want to keept the older presentation

**Comment by Frank-Zappa** [comment]
I think the redefinition of the ´\@makefntext´ is a silly thing. It breaks the compatibility with memoir class and doesn't take into considerations that French is used as other languages with `\setotherlanguages{french}`. See: http://tex.stackexchange.com/questions/334570

Please revert this!

**Comment by flueterflam** [comment]
I agree with @Frank-Zappa .  I use polyglossia with `\setotherlanguage{french}` with the `memoir` class and this really messes up my footnotes.  I  only use French because there are a couple block quotes in my thesis, which don't have any French in the footnotes.  The main document language is English.

There should be some checking of *how* French is defined as a language within the document.  If not the main language, this redefinition of `@makefntext` should not occur.  A package option could be used to force this setting, if desired by the user.

**Comment by bastien-roucaries** [comment]
Agreed will take it

**Comment by jspitz** [comment]
The `\@makefntext` issue is #157 and fixed.

Everything else is implemented (since a long time).

Please close the ticket.
