### ISSUE TITLE
New LaTeX error with variant=british

### ISSUE THREAD

**Issue by jspitz** [reutenauer/polyglossia#163]
The following example does not compile with LuaTeX:

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont[Ligatures=TeX]{DejaVu Serif}
\setsansfont[Ligatures=TeX]{DejaVu Sans}
\setmonofont{DejaVu Sans Mono}

\usepackage{polyglossia}
\setdefaultlanguage{german}
\setotherlanguage{english}

\begin{document}

Test Test \textenglish[variant=british]{test}
\textenglish[variant=british]{test} Test Test Test Test Test 
Test Test Test Test Test

\end{document}
```

The error messages are:

```
! Undefined control sequence.
\english@language ->\language =\l@ukenglish 
                                            \xpg@set@language@luatex@ii {uke...
l.14 \textenglish[variant=british]{test}
                                       Test Test Test Test Test
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! You can't use `\relax' after \the.
<recently read> \l@ukenglish 

l.14 \textenglish[variant=british]{test}
                                       Test Test Test Test Test
I'm forgetting what you said and using zero instead.

! Missing number, treated as zero.
<to be read again> 
\def 
l.14 \textenglish[variant=british]{test}
                                       Test Test Test Test Test
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
```

This is with polyglossia 1.42.4. The bug seems to have been introduced by https://github.com/reutenauer/polyglossia/commit/d74a64b681b12555f61f30e4a73af3c891c22155

**Comment by reutenauer** [comment]
Hi Jürgen,

Thank you for the bug report.  I’m afraid it’s actually more complicated than that: bug #129 is ultimately caused by a fundamental change in the LuaTeX format, that I don’t have control over, and the commit you refer to introduced completely new code to deal with that change; I thought I had addressed all the important use cases but it’s quite possible I missed some of them.  I’ll look into that.

Very briefly, the change in the format is that all the `l@<language>` control sequences, that define the sets of hyphenation patterns, were entirely removed, and Polyglossia thus has to rely on other information to find out which patterns are present.

**Comment by fiapps** [comment]
I'm getting errors in a document with XeLaTeX if I use `\textenglish[variant=british]{…}`. It's a very long document, so I haven't narrowed the issue to a MWE, but I get a complaint about an unmatched `\else`. I note that if I typeset the document above with XeLaTeX (TeXLive 2017, polyglossia 2015/03/25 v1.42.4), I get two warnings of this form: `(\end occurred when \ifx on line X was incomplete)`, where X is a line number containing `\textenglish[variant=british]{…}`.

It looks like the code executed by `\textenglish[variant=british]{test}` contains an `\ifx` that isn't closed. In my document there's a `\fi` that's supposed to go with my `\else`, but since `\textenglish[variant=british]{…}` is used between the `\else` and the `\fi`, XeLaTeX thinks my `\fi` goes with `\polyglossia`'s `\ifx`, and considers my `\else` unmatched.

**Comment by jspitz** [comment]
I cannot reproduce any longer with the development version in the repo. Probably fixed in the wake of the language setting changes.
