### ISSUE TITLE
\normalfont doesn't work as expected

### ISSUE THREAD

**Issue by eg9** [reutenauer/polyglossia#203]
With the following document the text is printed in italics.

```latex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[Script=Cyrillic]{serbian}
\setmainfont{CMU Serif}[
  Language=Serbian,
  Script=Cyrillic,
]

\begin{document}

\itshape\normalfont\bfseries Test

\fontname\font

\end{document}
```

<img width="845" alt="screen shot 2018-03-18 at 22 43 47" src="https://user-images.githubusercontent.com/302839/37571522-f22215c8-2afd-11e8-9b92-883b4231db0f.png">

If `\setmainlanguage[Script=Cyrillic]{serbian}` is commented out, the text is in upright boldface.

**Comment by jspitz** [comment]
The problem here is that latex defines `\normalfont` as
```
\DeclareRobustCommand\normalfont
                 {\usefont\encodingdefault
                          \familydefault
                          \seriesdefault
                          \shapedefault
                  \relax}
```
so it does reset family, series and shape (and encoding), while polyglossia only resets the family (via `\xpg@select@fontfamily`).

I don't see how one can get the default series or shape for a given language/script font from polyglossia or fontspec. Glimpsing through both sources, it strikes me this is not provided.

An easy fix would be
```
diff --git a/tex/polyglossia.sty b/tex/polyglossia.sty
index 5178461..579f31d 100644
--- a/tex/polyglossia.sty
+++ b/tex/polyglossia.sty
@@ -760,7 +760,7 @@
   \letcs{\rmfamily}{#1@font@rm}%
   \letcs{\sffamily}{#1@font@sf}%
   \letcs{\ttfamily}{#1@font@tt}%
-  \gdef\normalfont{\protect\xpg@select@fontfamily{#1}}%
+  \gdef\normalfont{\normalfontlatin\protect\xpg@select@fontfamily{#1}}%
   \gdef\reset@font{\protect\normalfont}%
 }
```

at least unless we have default series and shape information.

Opinions?

**Comment by jspitz** [comment]
> I don't see how one can get the default series or shape for a given language/script font from polyglossia or fontspec. Glimpsing through both sources, it strikes me this is not provided.

Actually, it is:

```
\fontseries{\seriesdefault}\selectfont
\fontshape{\shapedefault}\selectfont
```
