### ISSUE TITLE
Language variants must be loaded in `\set*language`

### ISSUE THREAD

**Issue by svenper** [reutenauer/polyglossia#208]
Using language variants requires passing the variant first as an option to `\set*language`, or it will [fail (`lualatex`)](https://gist.githubusercontent.com/svenper/14a11aac1ecbfc3fc4f081c8a9328db7/raw) or print [warnings (`xelatex`)](https://gist.githubusercontent.com/svenper/0c0b1499b59da89855adf8b8a268c599/raw). `xelatex` prints the warnings even when declaring the variants.

Perhaps the documentation is unclear (or I am missing something).

```tex
\documentclass{article}
\usepackage{polyglossia}
%\setmainlanguage[variant=british,variant=usmax]{english}
\setmainlanguage{english}
\begin{document}
\begin{english}[variant=british]analogue\end{english}
\begin{english}[variant=usmax]analog\end{english}
\end{document}
```

(Continuation of plk/biblatex#777)

**Comment by jspitz** [comment]
This problem only applies to English. The reason is that `\english@language` is only defined in the variant key setting.

I have a patch in the pipe which fixes this and also cleans up a bit the rather messy variant parser in gloss-english.

As soon as my pull request queue is free, I will propose the fix.
