### ISSUE TITLE
Clean up polyglossia.newloader

### ISSUE THREAD

**Issue by reutenauer** [reutenauer/polyglossia#283]
It is messy.  As part of the same effort, remove `xpg@set@language@luatex@ii` (unused), and rename the corresponding `...@iii` and `...@iv` to something more meaningful.

**Comment by jspitz** [comment]
Also, we have in many gloss files code like
```
   \ifxetex
      \language=\csname l@\french@variant\endcsname
   \fi
   \ifluatex
      \xpg@set@language@luatex@iv{\french@variant}
   \fi
```
This (the engine check) could be done in a dedicated command, so that gloss files only need to call e.g.
`\setlanguagename{\french@variant}`

I think there are only very few gloss files that do not use `\xpg@set@language@luatex@iv` for luatex. These should be audited. I suspect the `@iv` function is the right one for all languages nowadays.

**Comment by reutenauer** [comment]
Yes, it should work for any language with LuaTeX; I wrote it for that purpose.  Only the name should be changed: `iv` was purely chronological, that’s the fourth macro I wrote that worked for all cases :-)  And contrary to what I wrote [just earlier](282#issuecomment-527323558), this particular one was from 3½ years, not 7 years.

**Comment by jspitz** [comment]
> As part of the same effort, remove `xpg@set@language@luatex@ii` (unused), and rename the corresponding `...@iii` and `...@iv` to something more meaningful.

This has been done at c0c999037970c77 (except for one `...@ii` remainder which awaits gloss-latin rewrite.

The generic loader rewrite seems to be subject of #302.

**Comment by jspitz** [comment]
Is there anything left to d0 after afeca0f0346?

**Comment by jspitz** [comment]
@reutenauer do you have more cleanup in mind after @dohyunkim's cleanup?

**Comment by reutenauer** [comment]
No, that seems fine.  Thanks!

**Comment by reutenauer** [comment]
No, that seems fine.  Thanks!
