### ISSUE TITLE
\localnumber or \localnumerals?

### ISSUE THREAD

**Issue by reutenauer** [reutenauer/polyglossia#287]
I‘m thinking of systematically renaming `\localnumber` to `\localnumerals`.  Rationale: “numerals” is used and documented as an option to several languages, and `\localnumerals` would be consistent with that.  Also, it removes the possible confusion with the primitive `\number`.  We haven’t yet released `\localnumber` to CTAN, so now would be the time.

We don’t have to rename all the internal macros and functions but it would be good to have consistent names in the user interface.

Anyone opposed?

**Comment by jspitz** [comment]
The only point I'd have is that it is longer to type. But I am fine with the renaming.

**Comment by jspitz** [comment]
But the, why plural, not `\localnumeral`? The macro only outputs one number AFAIK.

**Comment by reutenauer** [comment]
The option name is in the plural (for Arabic, Bengali, Persian, Greek, Hebrew, etc.); I think that’s because “numeral” is understood as meaning one single digit, hence a number is referred to as “numerals”.  Or perhaps because there (usually) are ten of them in each system :-)

**Comment by jspitz** [comment]
>
> The option name is in the plural (for Arabic, Bengali, Persian, Greek,
> Hebrew, etc.); I think that’s because “numeral” is understood as meaning
> one single digit, hence a number is referred to as “numerals”. Or perhaps
> because there (usually) are ten of them in each system :-)
>
I think the latter. I don't mean to change the option name.

>

**Comment by jspitz** [comment]
I have now added some documentation at https://github.com/reutenauer/polyglossia/commit/5cbd9eb215ac4b312f2d3fd62fda1bcb9869d3fd, so if you rename, please update the documentation as well.

Having documented it, I think it would make sense to have `\localnumeral` and `\Localnumeral` for the upper- and lowercased formats (where applicable) and a starred form `\localnumeral*` and `\Localnumeral*` which take counters rather than digits as input.

Currently, `\localnumber` takes a counter, `\Localnumber` a digit, and we have no way to change casing.

**Comment by jspitz** [comment]
I have renamed it to `\localnumeral` now.
