### ISSUE TITLE
Sanskrit for LuaTeX

### ISSUE THREAD

**Issue by jspitz** [reutenauer/polyglossia#336]
`gloss-sanskrit` lacks luatex support (punctuation spacing).

@wehro I figure this will be more easy now to implement after your recent changes. Want to have a go at it?

**Comment by wehro** [comment]
> @wehro I figure this will be more easy now to implement after your recent changes. Want to have a go at it?

Yes, it should be easy. Can someone state a font supporting Devanagari? I need it for testing.

**Comment by jspitz** [comment]
Noto Serif Davanagari:
https://www.google.com/get/noto/#serif-deva

**Comment by wehro** [comment]
OK, I have implemented the same spacing as with XeTeX.
But I am not sure if it is wise to insert a thinspace before the Devanagari “danda” and “double danda” punctuation. The font suggested by Jürgen already has some kerning here.
Furthermore, I noticed that the same word is rendered totally different with LuaTeX. So implementing the spacing will not be enough for full LuaTeX support of (Devanagari) Sanskrit.

Please have a look:

1. XeTeX without spacing before danda and double danda, but with thinspaces before other punctuation
![XeTeX_ohne](https://user-images.githubusercontent.com/33468411/67975914-527dce00-fc15-11e9-8b3c-2257db3149a4.png)
2. XeTeX with a thinspace before all punctuation
![XeTeX_mit](https://user-images.githubusercontent.com/33468411/67976087-b607fb80-fc15-11e9-901b-44353b6d9d17.png)
3. LuaTeX without spacing before danda and double danda, but with thinspaces before other punctuation
![LuaTeX_ohne](https://user-images.githubusercontent.com/33468411/67976111-c0c29080-fc15-11e9-9c75-83cece8a01e8.png)
4. LuaTeX with a thinspace before all punctuation
![LuaTeX_mit](https://user-images.githubusercontent.com/33468411/67976260-0b440d00-fc16-11e9-9108-ff9f28e66e27.png)

The source file is:
```
\documentclass[12pt]{article}
\usepackage{polyglossia}
\setmainlanguage{sanskrit}
\newfontfamily\devanagarifont{Noto Serif Devanagari}

\begin{document}
\noindent
विद्यार्थी!\\विद्यार्थी?\\विद्यार्थी।\\विद्यार्थी॥\\विद्यार्थी:\\विद्यार्थी;
\end{document}
```
As far as I can judge it, half a thinspace would be better before a danda, at least with this font.
Unfortunately, I know next to nothing about Devanagari and Sanskrit. So please tell me what you consider correct.

By the way, what is the `\today` command expected to yield within a Sanskrit environment? I just get some empty boxes instead of a month name.

**Comment by jspitz** [comment]
> I noticed that the same word is rendered totally different with LuaTeX. So implementing the spacing will not be enough for full LuaTeX support of (Devanagari) Sanskrit.

Probably a LuaTeX deficiency as indicated in https://github.com/reutenauer/polyglossia/issues/337#issuecomment-547776331

> Please have a look:

I no nothing about Devanagari script, so I cannot judge. I would just emulate with LuaTeX XeTeX output as far as possible. I suppose the people who have implemented the XeTeX kernings knew what they did.

> By the way, what is the `\today` command expected to yield within a Sanskrit environment? I just get some empty boxes instead of a month name.

`\datesanskrit` is not yet implemented (neither `\captions`). Since there seems to be no other sanskrit localization package available we could check, we need somebody with respective linguistic competence.

**Comment by jspitz** [comment]
The punctuation code has been merged. The remainder is an usptream (LuaTeX) issue.
