### ISSUE TITLE
Invalid bcp47 tags

### ISSUE THREAD

**Issue by jbezos** [reutenauer/polyglossia#385]
At least the following tags are invalid:

```
de-AT-1901-Latf
de-AT-1996-Latf
de-CH-1901-Latf
de-CH-1996-Latf
de-CH-1901-Latf
de-DE-1996-Latf
la-xclassic
la-xmedieval
la-xecclesiastic
```

The tags for German should be either `de-Latf-DE-1901` or `de-CH-1901-x-Latf`, etc.

The tags for Latin must have an additional hyphen: `la-x-classic`. In addition, `ecclesiastic` must be shortened to 8 letters.

**Comment by jspitz** [comment]
Thanks for the report, @jbezos.

>  In addition, `ecclesiastic` must be shortened to 8 letters.

Could you give a reference for this? I did not find this in the BCP-47 specifications (sec. 4.4.1 only gives length limitations for `language`, `script`, `region`, `variants`, and total, not for `private-use`; the total of 35 chars is not exceeded here either)

Everything else has been fixed (the `x-` at beefa74691)

**Comment by jspitz** [comment]
Never mind, found it (sec. 2.2.7):

> Private use subtags MUST conform to the format and content
>        constraints defined in the ABNF for all subtags; that is, they
>        MUST consist solely of letters and digits and not exceed eight
>        characters in length.

**Comment by jbezos** [comment]
Hyphenation patterns are identified as `la-x-liturgic`. Perhaps this is a better name (not sure right now).

Anyway, as I said, there are some loose ends and I don't want to rush. I'll include the data in the locale ini files for sure (after all, they where initially devised as a shared resource for both babel and polyglossia, as well as other packages), but I'm not sure when (very likely by Spring). If you or Arthur ( @reutenauer ) think there is other data which can be useful, just let me know (you can even open an issue or do a pull request).

**Comment by jspitz** [comment]
> Hyphenation patterns are identified as `la-x-liturgic`. Perhaps this is a better name (not sure right now).

I'm not sure either. @wehro what's your opinion on that?

**Comment by jspitz** [comment]
Note, though, that, for reasons I don't know, the `ecclesiastic` variety does not use the liturgical patterns, but the classic ones (same for the `ecclesiastic` package that is used with babel, which might be the reason). So using `la-x-liturgic` might insinuate a wrong relation, actually.

**Comment by wehro** [comment]
> Note, though, that, for reasons I don't know, the `ecclesiastic` variety does not use the liturgical patterns, but the classic ones

No, the default for ecclesiastic Latin are the *modern* hyphenation patterns. The reason is that these patterns correspond to the traditional hyphenation style of ecclesiastical documents and liturgical books (more or less), which is strongly influenced by Italian typography.
The so-called *liturgical* patterns are relatively new. The rules which they are based on have been developed by French monasteries some years ago. They are based on Italian phonetics in a stricter manner than the modern patterns. These rules aim to make chanting easier. These patterns are too young to claim universal acceptance by typesetters of liturgical books. They should only be available as an option.
Only if the traditional German (or Slavic) pronunciation of Latin (which is quite different from the Italian pronunciation) is used, I personally would recommend the classical patterns.
Further details can be found [here](https://github.com/gregorio-project/hyphen-la/tree/master/doc#hyphenation-styles).

> So using `la-x-liturgic` might insinuate a wrong relation, actually.

Indeed.

**Comment by jspitz** [comment]
Thanks for the detailed explanation, Keno. So we'll stick with `la-x-ecclesia` for the time being.
