### ISSUE TITLE
Date in Serbian/Croatian Text

### ISSUE THREAD

**Issue by aleslavista** [reutenauer/polyglossia#524]
Hello,
When executing command \today in Serbian or Croatian text, months should be inflected in the genitive case: here are the correct Serbian forms both in Cyrillic and Latin script:

```
јануара / januara
фебруара / februara
марта / marta
априла / aprila
маја / maja
јуна / juna
јула / jula
августа / avgusta
септембра / septembra
октобра / oktobra
новембра / novembra
децембра / decembra
```

And here are the correct Croatian forms:

```
siječnja
veljača
ožujka
travnja
svibnja
lipnja
srpnja
kolovoza
rujna
listopada
studenoga
prosinca
```

**Comment by ivankokan** [comment]
> Hello, When executing command \today in Serbian or Croatian text, months should be inflected in the genitive case: here are the correct Serbian forms both in Cyrillic and Latin script:
> 
> ```
> јануара / januara
> фебруара / februara
> марта / marta
> априла / aprila
> маја / maja
> јуна / juna
> јула / jula
> августа / avgusta
> септембра / septembra
> октобра / oktobra
> новембра / novembra
> децембра / decembra
> ```
> 
> And here are the correct Croatian forms:
> 
> ```
> siječnja
> veljača
> ožujka
> travnja
> svibnja
> lipnja
> srpnja
> kolovoza
> rujna
> listopada
> studenoga
> prosinca
> ```

Croatian is already fully covered (considering you have a typo veljač**a**).

**Comment by aleslavista** [comment]
Sorry, never mind it's **veljače** :(

**Comment by ivankokan** [comment]
I agree with the proposed changes for Serbian.

**Comment by jspitz** [comment]
@ivankokan I understand you will provide a pull request for Serbian?

**Comment by ivankokan** [comment]
> @ivankokan I understand you will provide a pull request for Serbian?

Done and ready to be merged.

**Comment by ivankokan** [comment]
I sent this to babel-serbian(c) maintainers as well.

**Comment by ivankokan** [comment]
Since babel-serbian(c) maintainers were suspicious about this and reluctant to immediately make changes on their side, I have asked the Матица српска (https://en.wikipedia.org/wiki/Matica_srpska) about this. This is what I received:

> Правопис српскога језика не прописује експлицитно писање датума, то питање ће, надам се, бити решено у неком од следећих издања.
> Уобичајена пракса писања датума има три облика (тако и деца уче у школи):
> 2. 6. 2022.
> 2. VI 2022.
> 2. јун 2022.
> Ја највише волим овај последњи и тако увек пишем. Када се наводи назив месеца уместо цифре, онда се именица употребљава у номинативу, не у генитиву. За шести и седми месец равноправне варијанте су јуни и јули, мени је ближе јун и јул. Генитив од јун и јул гласе јуна и јула, не *јунија или *јулија.



Summary:
- There are no explicit rules on typesetting dates, that will (hopefully) be covered in future editions.
- There are three acceptable variants in "standalone form", e.g. for the D=2, M=6/7, Y=2022:
1. 2. 6. 2022. / 2. 7. 2022.
2. 2. VI 2022. / 2. VII 2022.
3. 2. јун 2022. (2. јуни 2022.) / 2. јул 2022. (2. јули 2022.) - all in the nominative case (the variants in the parenthesis are supported in babel with option `datei`).
- The genitive case for month names is used only when the date is an integral part of the sentence. For June and July, those are јуна and јула, respectively (irrelevant of the variant in the nominative case).

TODO:
- Implement `datei` option
- Implement `\todayArabic[*]`
- Implement `\todayGen[*]`

**Comment by jspitz** [comment]
So things are still pending, right?

**Comment by ivankokan** [comment]
> So things are still pending, right?

Yes, I will try to implement this today.

**Comment by ivankokan** [comment]
> To sum it up, apparently months in the Serbian variant do **not** take genitive endings when they stand alone. However in the Croatian variant, they ought to be in the genitive case all the time. Don't they?

Croatian: genitive all the time
Croatian: nominative in "standalone form" (e.g. somewhere in the corner when one writes a letter `Beograd, 2. jun 2022.`), genitive when the date is integral part of the sentence (e.g. `Bio sam u Beogradu 2. juna 2022.`).

**Comment by jspitz** [comment]
@ivankokan if you want to have this in polyglossia 1.54 you should hurry up. I will try to prepare the release over this weekend.

**Comment by jspitz** [comment]
I went ahead and implemented it myself. Testing welcome.
