### ISSUE TITLE
Unable to change `\proofname` when working with `amsthm`

### ISSUE THREAD

**Issue by YDX-2147483647** [reutenauer/polyglossia#545]
## To Reproduce

```latex
\documentclass{article}

\usepackage{amsthm}
\renewcommand*{\proofname}{The Proof}

\usepackage{polyglossia}

\begin{document}

\begin{proof}
    (whatever)
\end{proof}

\end{document}
```

This would generate something like the following.

> _Proof_. (whatever) □

## Expected

> _The Proof_. (whatever) □

Comment the `\usepackage{polyglossia}` would work as expected.

## More Info

Tested on my local XeLaTeX, XeLaTeX on Overleaf and LuaLaTeX on Overleaf. (TeX Live 2021)

I guess some commands conflict with `amsthm`, but no error has been raised…

(Thanks in advance :-)

**Comment by jspitz** [comment]
`\proofname` is redefined in the polyglossia language definition files, so you need to redefine it there. In your case, since you define no language, this is the default ldf `latex`. The following works:

```tex
\documentclass{article}

\usepackage{amsthm}

\usepackage{polyglossia}

\appto\captionslatex{
	\renewcommand*{\proofname}{The Proof}
}

\begin{document}
	
\begin{proof}
	(whatever)
\end{proof}
	
\end{document}
```

Use `\appto\captionsenglish` for English language context (e.g., with `\setmainlanguage{english}`).

**Comment by YDX-2147483647** [comment]
Thanks!
