### ISSUE TITLE
french and itemize: babel imitation

### ISSUE THREAD

**Issue by maieul** [reutenauer/polyglossia#89]
Hi, 

for french, the itemize environnement should not produce bullet, but dashes (as with the babel).

**Comment by hugoroy** [comment]
FYI, you can do this:

  \renewcommand{\labelitemi}{--}

in your document's preamble.

**Comment by maieul** [comment]
of course, but as polyglossia is for localization, it should be normal to use standard typographie of local language...

**Comment by hugoroy** [comment]
I agree, I was giving you what I am doing right now :-) I haven't looked into how to fix this in the package yet. Before trying to fix it, I'd like to see how to make it optionable so that in case people prefer the bullets, they would be able to load the French as `\setmainlanguage[liststyle=false]{french}` or something like that.

**Comment by jspitz** [comment]
I have added the respective options to 1.46. For backwards compatibility reasons, they are off by default.
