### ISSUE TITLE
Alternative to “\DeclareOption{british}{\xpg@option{variant=british}{english}}”?

### ISSUE THREAD

**Issue by nickbart1980** [reutenauer/polyglossia#97]
Why is “\DeclareOption{british}{\xpg@option{variant=british}{english}}” described as “deprecated” (https://github.com/reutenauer/polyglossia/blob/master/tex/polyglossia.sty#L821)?

And is there any recommended alternative to this for defining custom shorthands for languages and language variants?

**Comment by reutenauer** [comment]
Because it is :-)  As you can see, the lines that define package-wide options are commented out, so you can't use them any more (it's thus more correct to say that it is *unsupported*).  The recommended use is to pass an option to ` \setmainlanguage` and similar commands.

**Comment by nickbart1980** [comment]
OK, but obviously this syntax can even now be used to define, e.g., the custom synonym “en-GB” using `\DeclareOption{en-GB}{\xpg@option{variant=british}{english}}`. Is there anything fundamentally wrong with this, or do I have to expect changes in polyglossia that would break this anytime soon?

**Comment by reutenauer** [comment]
Well, if you fork Polyglossia and add that line, you’ll be able to load Polyglossia as `\usepackage[en-GB]{polyglossia}`, but I don’t think it’s a good idea, it would be far better to define a new command and write `\setmainlanguagecode[en-GB]` (or something like that) rather than set unrelated options at the package level.  The latter is the historical Babel syntax and it’s not particularly compelling.  I have it in the works to list the exact of all languages and language variants and add a command such as `\setmainlanguagecode`.

**Comment by reutenauer** [comment]
I’m closing the issue as it’s not clear that there’s anything that can be done to fix it.
